'apps: web':
  - changed-files:
      - any-glob-to-any-file: 'apps/remix/**'

'type: documentation':
  - changed-files:
      - any-glob-to-any-file: 'apps/docs/**'

'version bump 👀':
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - '**/package-lock.json'

'🚨 migrations 🚨':
  - changed-files:
      - any-glob-to-any-file: 'packages/prisma/migrations/**/migration.sql'

'🚨 e2e changes 🚨':
  - changed-files:
      - any-glob-to-any-file: 'packages/app-tests/e2e/**'

'🚨 .env changes 🚨':
  - changed-files:
      - any-glob-to-any-file: '.env.example'

'pkg: ee changes':
  - changed-files:
      - any-glob-to-any-file: 'packages/ee/**'
