// scripts/dev-657-setup-template-fields.ts
//
// Places all merge fields on the DEV-713 buyer-rep template via the Reeve.Sign
// v2 API. Idempotent enough for first-write — pass FORCE=1 to delete existing
// fields and re-create from scratch.
//
// This is THE pattern for scripted template field placement. We will reuse it
// for every future AgentPik (and other consumer) template. The field layout
// here is keyed to the PDF generated by `dev-657-generate-placeholder-pdf.ts`;
// if the PDF layout changes, update FIELD_LAYOUT here.
//
// Coordinate system:
//   - Source PDF uses pt (1pt = 1/72in), origin bottom-left, Y up
//   - Reeve.Sign (Documenso) uses % of page, origin top-left, Y down
//   - PDF page: US Letter 612 x 792 pt
//
// Run:
//   REEVE_SIGN_API_TOKEN=api_xxx TEMPLATE_ID=1 npx tsx scripts/dev-657-setup-template-fields.ts
//
// Env:
//   REEVE_SIGN_API_TOKEN   required — Bearer token (organisation-scoped)
//   TEMPLATE_ID            required — the templateId to place fields on
//   REEVE_SIGN_BASE_URL    optional — defaults to https://sign.meetreeve.com
//   FORCE                  optional — if "1", deletes any existing template fields before placing new ones

const PAGE_W = 612;
const PAGE_H = 792;
const FIELD_W_PT = 260;
const FIELD_H_PT = 20;

// PDF label positions (label text drawn at (x, y), underline at y-4).
// Field placed so its bottom edge sits on the underline.
type FieldLayout = {
  id: string; // snake_case label — matches formValues key in the envelope-create payload
  type: 'TEXT' | 'EMAIL' | 'NUMBER' | 'DATE' | 'DROPDOWN' | 'SIGNATURE';
  page: number; // 1-indexed
  xPt: number;
  yPt: number; // PDF Y (bottom-left origin) of the LABEL — underline is at yPt-4
  widthPt?: number;
  heightPt?: number;
  // Dropdown values
  options?: string[];
  // Default value (rendered, signer-editable unless readonly:true)
  defaultValue?: string | number;
  // Read-only at signing time
  readonly?: boolean;
  // Required at signing time (most fields are required; signing_date is auto)
  required?: boolean;
  // Friendly label shown in the editor
  label?: string;
};

const FIELD_LAYOUT: FieldLayout[] = [
  // Page 1: parties
  { id: 'agent_name', type: 'TEXT', page: 1, xPt: 36, yPt: 638, readonly: true, label: 'Agent name' },
  { id: 'agent_license_number', type: 'TEXT', page: 1, xPt: 36, yPt: 612, readonly: true, label: 'Agent CA DRE #' },
  { id: 'consumer_name', type: 'TEXT', page: 1, xPt: 36, yPt: 586, readonly: true, label: 'Consumer name' },
  { id: 'consumer_email', type: 'EMAIL', page: 1, xPt: 36, yPt: 560, readonly: true, label: 'Consumer email' },
  { id: 'consumer_phone', type: 'TEXT', page: 1, xPt: 36, yPt: 534, label: 'Consumer phone' },
  // Page 1: scope
  {
    id: 'property_type',
    type: 'DROPDOWN',
    page: 1,
    xPt: 36,
    yPt: 468,
    options: ['SFH', 'Condo', 'Multi-family', 'TBD'],
    label: 'Property type',
  },
  { id: 'search_area', type: 'TEXT', page: 1, xPt: 36, yPt: 442, label: 'Search area (city/zip)' },
  { id: 'term_days', type: 'NUMBER', page: 1, xPt: 36, yPt: 416, defaultValue: 90, label: 'Term (days)' },
  // Page 2: compensation
  { id: 'commission_percent', type: 'NUMBER', page: 2, xPt: 36, yPt: 698, defaultValue: 2.5, label: 'Commission %' },
  // Page 2: signature row
  {
    id: 'consumer_signature',
    type: 'SIGNATURE',
    page: 2,
    xPt: 36,
    yPt: 568,
    widthPt: 200,
    heightPt: 30,
    label: 'Consumer signature',
  },
  { id: 'signing_date', type: 'DATE', page: 2, xPt: 320, yPt: 568, label: 'Signing date' },
];

// Convert a labeled-line PDF anchor to Documenso percentage coords.
// Field rests with its bottom on the underline of the label (yPt - 4 in PDF space).
function toDocumensoCoords(layout: FieldLayout) {
  const w = layout.widthPt ?? FIELD_W_PT;
  const h = layout.heightPt ?? FIELD_H_PT;

  // PDF coords of field top-left:
  // - x is the label x
  // - underline is at yPt - 4 (PDF Y, bottom-left origin)
  // - field bottom edge sits on the underline
  // - field top edge is underline + h = (yPt - 4) + h
  const topYPdf = layout.yPt - 4 + h;
  const leftXPdf = layout.xPt;

  // Documenso top-left origin in %:
  return {
    pageX: round2((leftXPdf / PAGE_W) * 100),
    pageY: round2(((PAGE_H - topYPdf) / PAGE_H) * 100),
    width: round2((w / PAGE_W) * 100),
    height: round2((h / PAGE_H) * 100),
  };
}

function round2(n: number) {
  return Math.round(n * 100) / 100;
}

function need(name: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(`Missing required env var: ${name}`);
    process.exit(1);
  }
  return v;
}

async function api<T>(
  baseUrl: string,
  token: string,
  path: string,
  init: RequestInit & { method?: string },
): Promise<T> {
  const res = await fetch(`${baseUrl}${path}`, {
    ...init,
    headers: {
      Authorization: token,
      'Content-Type': 'application/json',
      ...(init.headers ?? {}),
    },
  });
  const text = await res.text();
  let body: unknown;
  try {
    body = JSON.parse(text);
  } catch {
    body = text;
  }
  if (!res.ok) {
    console.error(`HTTP ${res.status} ${res.statusText} on ${init.method ?? 'GET'} ${path}`);
    console.error(JSON.stringify(body, null, 2));
    process.exit(1);
  }
  return body as T;
}

type Template = {
  id: number;
  title: string;
  teamId: number;
  recipients: { id: number; role: string; email: string; name: string }[];
  fields?: { id: number }[];
};

async function main() {
  const baseUrl = process.env.REEVE_SIGN_BASE_URL ?? 'https://sign.meetreeve.com';
  const token = need('REEVE_SIGN_API_TOKEN');
  const templateId = Number(need('TEMPLATE_ID'));
  const force = process.env.FORCE === '1';

  console.log(`→ GET /api/v2/template/${templateId}`);
  const tpl = await api<Template>(baseUrl, token, `/api/v2/template/${templateId}`, { method: 'GET' });
  console.log(`  title: ${tpl.title}`);
  console.log(`  teamId: ${tpl.teamId}`);
  console.log(`  recipients: ${tpl.recipients.length}`);
  console.log(`  existing fields: ${tpl.fields?.length ?? 0}`);

  if (tpl.recipients.length === 0) {
    console.error(
      'Template has no recipient slots. Add a SIGNER recipient in the UI (or via ' +
        '/api/v2/template/recipient/create) before running this script.',
    );
    process.exit(1);
  }
  const signer = tpl.recipients.find((r) => r.role === 'SIGNER') ?? tpl.recipients[0]!;
  console.log(`  signer recipientId: ${signer.id}`);

  if ((tpl.fields?.length ?? 0) > 0) {
    if (!force) {
      console.error(`Template already has ${tpl.fields!.length} fields. Pass FORCE=1 to delete and recreate.`);
      process.exit(1);
    }
    console.log(`→ FORCE=1, deleting ${tpl.fields!.length} existing fields...`);
    for (const f of tpl.fields!) {
      await api(baseUrl, token, `/api/v2/template/field/delete`, {
        method: 'POST',
        body: JSON.stringify({ fieldId: f.id }),
      });
      console.log(`  deleted field ${f.id}`);
    }
  }

  // Build fields array. Documenso's field-create schema is a discriminated union on `type`.
  const fields = FIELD_LAYOUT.map((layout) => {
    const coords = toDocumensoCoords(layout);
    const base = {
      recipientId: signer.id,
      pageNumber: layout.page,
      pageX: coords.pageX,
      pageY: coords.pageY,
      width: coords.width,
      height: coords.height,
    };

    // Build fieldMeta per type. snake_case label is required for envelope-create
    // formValues lookup; it's the "name" / "label" field on most Documenso field-meta shapes.
    const commonMeta = {
      label: layout.label ?? layout.id,
      readOnly: layout.readonly ?? false,
      required: layout.required ?? layout.type !== 'DATE',
    };

    switch (layout.type) {
      case 'TEXT':
        return {
          ...base,
          type: 'TEXT',
          fieldMeta: {
            ...commonMeta,
            type: 'text',
            text: layout.defaultValue !== undefined ? String(layout.defaultValue) : undefined,
          },
        };
      case 'EMAIL':
        return {
          ...base,
          type: 'EMAIL',
          fieldMeta: { ...commonMeta, type: 'email' },
        };
      case 'NUMBER':
        return {
          ...base,
          type: 'NUMBER',
          fieldMeta: {
            ...commonMeta,
            type: 'number',
            value: layout.defaultValue !== undefined ? String(layout.defaultValue) : undefined,
          },
        };
      case 'DATE':
        return {
          ...base,
          type: 'DATE',
          fieldMeta: {
            ...commonMeta,
            type: 'date',
            required: false,
            readOnly: true,
          },
        };
      case 'DROPDOWN':
        return {
          ...base,
          type: 'DROPDOWN',
          fieldMeta: {
            ...commonMeta,
            type: 'dropdown',
            values: (layout.options ?? []).map((v) => ({ value: v })),
          },
        };
      case 'SIGNATURE':
        return {
          ...base,
          type: 'SIGNATURE',
          fieldMeta: {
            ...commonMeta,
            type: 'signature',
            readOnly: false,
          },
        };
    }
  });

  console.log(`→ POST /api/v2/template/field/create-many (${fields.length} fields)`);
  const result = await api<{ fields: { id: number; type: string }[] }>(
    baseUrl,
    token,
    `/api/v2/template/field/create-many`,
    {
      method: 'POST',
      body: JSON.stringify({ templateId, fields }),
    },
  );

  console.log(`✓ Created ${result.fields.length} fields`);
  for (const f of result.fields) {
    console.log(`  ${f.type} #${f.id}`);
  }
  console.log('');
  console.log(`Done. Inspect: https://sign.meetreeve.com/o/<org>/t/${templateId}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
